### ISSUE TITLE
500 Internal Server Error for /rest-auth/password/reset/

### ISSUE THREAD

**Issue by ZachLiuGIS** [Tivix/django-rest-auth#135]
When I tried to use the /rest-auth/password/reset/ endpoint to reset password, I got this error. It was fine for v0.5, but not v0.6. Thanks.

Trackback:

```
Internal Server Error: /rest-auth/password/reset/
Traceback (most recent call last):
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/template/defaulttags.py", line 501, in render
    current_app=current_app)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
django.core.urlresolvers.NoReverseMatch: Reverse for 'project.password_reset_confirm' with arguments '()' and keyword arguments '{'uidb64': b'Mg', 'token': '47i-9050dc8d943a476f73b9'}' not found. 0 pattern(s) tried: []

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/rest_auth/views.py", line 112, in post
    serializer.save()
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/rest_auth/serializers.py", line 131, in save
    self.reset_form.save(**opts)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/contrib/auth/forms.py", line 256, in save
    html_email_template_name=html_email_template_name)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/contrib/auth/forms.py", line 206, in send_mail
    body = loader.render_to_string(email_template_name, context)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/template/defaulttags.py", line 40, in render
    output = self.nodelist.render(context)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/template/loader_tags.py", line 56, in render
    result = self.nodelist.render(context)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/utils/six.py", line 659, in reraise
    raise value
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Users/ZachLiu/.virtualenvs/property_365/lib/python3.4/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
django.core.urlresolvers.NoReverseMatch: Reverse for 'password_reset_confirm' with arguments '()' and keyword arguments '{'uidb64': b'Mg', 'token': '47i-9050dc8d943a476f73b9'}' not found. 0 pattern(s) tried: []
```

**Comment by sully90h** [comment]
This may be a duplicate of https://github.com/Tivix/django-rest-auth/issues/63. 

django-rest-auth relies on django.contrib.auth for password resets, but doesn't include the relevant URLs. Rather than including all of the django.contrib.auth.urls, I only included the ones I needed for password resets. When these are defined, the rest_auth URLs work as expected:

    from django.contrib.auth.views import password_reset, \
        password_reset_done, password_reset_confirm, password_reset_complete
    
    
    urlpatterns = [
    
        url(
            regex=r'^contrib/password_reset/$',
            view=password_reset,
            name='password_reset'
        ),
        url(
            regex=r'^contrib/password_reset/done/$',
            view=password_reset_done,
            name='password_reset_done'
        ),
        url(
            regex=r'^contrib/reset/(?P<uidb64>[0-9A-Za-z_\-]+)'
                  r'/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            view=password_reset_confirm,
            name='password_reset_confirm'
        ),
        url(
            regex=r'^contrib/reset/done/$',
            view=password_reset_complete,
            name='password_reset_complete'
        ),
    ]

Also, it looks like you're only passing the base64 UID and the token to the password_reset_confirm endpoint. It also requires the new password, and a confirmation. JSON would look like this:

    {
      'new_password1': '1234567890',
      'new_password2': '1234567890',
      'uid': 'MQ',
      'token': '47j-56c48c15a58706cee8c0'
    }

**Comment by Akay7** [comment]
I'm get some trouble a day ago, I thought that trouble must be documented.

**Comment by mariodev** [comment]
@ZachLiuGIS You need to add `password_reset_confirm` by yourself. Please check `urls.py` of the included demo app for more details.

**Comment by aspyct** [comment]
I had the same error when using django-rest-auth 0.9.0 with django-allauth 0.27.0.
This SO post solved my error: http://stackoverflow.com/questions/26869309/django-rest-framework-django-allauth-password-reset-recovery/36365644#36365644

I'll copy below in case it goes away. Since rest_framework beautifully integrates with allauth, I think this fix could be included in a future version.

> In case it helps, solved this problem by just created a new class to override the password serializer.
> 
> ```
> from rest_auth.serializers import PasswordResetSerializer
> from allauth.account.forms import ResetPasswordForm
> 
> class PasswordSerializer (PasswordResetSerializer):
>     password_reset_form_class = ResetPasswordForm
> ```
> Then make sure to add this to your settings:
> 
> ```
> REST_AUTH_SERIALIZERS = {
>     'PASSWORD_RESET_SERIALIZER': 'api.helpers.pwdreset.PasswordSerializer',
> }
> ```

**Comment by kjg531** [comment]
Almost 2 years later and @aspyct response is still a working fix.

**Comment by CavalcanteLucas** [comment]
I get this error: ValueError: not enough values to unpack (expected 2, got 1). Any idea what might be the cause?
