### ISSUE TITLE
giving "CSRF Failed: CSRF token missing or incorrect" while using both session and token login

### ISSUE THREAD

**Issue by sanchig** [Tivix/django-rest-auth#164]
We are using session login in website so user can multiple login and logout in multiple browser (It doesn't throw any error and keep current session while logout from another browser so we are using session login). 
we are using token login in mobile application but if we are logged in multiple mobile device its giving "CSRF Failed: CSRF token missing or incorrect" while logout from another mobile device. We are using token login in mobile app because User doesn't  need to re-login in it's own mobile(as any other app does)

I have tried https://github.com/Tivix/django-rest-auth/issues/16 solution and it solves mobile device problem(as mentioned in above)

REST_SESSION_LOGIN = False

But we want to use session login too. so user does not need to re-login while logged out from another device.

We have spend a lot of time for this solution but nothing is work. Please help us!! :)

**Comment by LeonardoGentile** [comment]
Have you seen #159?

**Comment by sanchig** [comment]
@LeonardoGentile I used this [http://www.soyoucode.com/2011/really-disable-csrf-django](url) solution and it works fine.

**Comment by sanchig** [comment]
@LeonardoGentile Can you explain how to and where to set this [url](https://github.com/Tivix/django-rest-auth/pull/181#issuecomment-188787499) code??. need to add any another url for LoginViewCustom class??. is there different url for session and token authentication? (I used both token and session auth)

**Comment by tezro** [comment]
I'm using DRF for the web app. Our iOS developer uses it using Swift. It's literally impossible to work when you can't be logged in all the time :)

**Comment by LeonardoGentile** [comment]
@sanchig I think my comment is quite clear, what is that you don't understand?
You have to crete a new app (`myapp` for example) and apply the code mentioned [here](https://github.com/Tivix/django-rest-auth/issues/159#issuecomment-173909852)

Basically you creates a new class view child of LoginView provided by django-rest-auth in order to include an extra `authentication_classes` field

**Comment by tezro** [comment]
Yeah I understand that. Although.
```
>>> from rest_framework.authentication import TokenAuthentication
>>> from rest_auth.registration.views import LoginView
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "d:\Projects\test\venv\lib\site-packages\rest_auth\registration\views.py", line 10, in <module>
    from allauth.account.views import ConfirmEmailView
ImportError: No module named allauth.account.views
```
It requires installing `allauth` module.

**Comment by cho-is** [comment]
@andreyshipilov I recommend you read the docs.

**Comment by andreyshipilov** [comment]
@cho-is I recommend you provide useful comments instead.

**Comment by cho-is** [comment]
@andreyshipilov do you have `rest_auth.registration` in your `INSTALLED_APPS`?

**Comment by andreyshipilov** [comment]
@cho-is yeah man. Basically I solved this problem temporarily by creating an endpoint for getting an CSRF token.

**Comment by woegjiub** [comment]
https://github.com/tomchristie/django-rest-framework/issues/3538#issuecomment-153375679

Tom Christie suggests that the login view should explicitly have no authentication classes.

Is there any chance of having that change implemented?

**Comment by Taniya2412** [comment]
Try including 
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    )
}

**Comment by dudanogueira** [comment]
@Taniya2412 suggestion will work, but you will only be able to use your API with token based auth. (Not even the browser navigation option will work). I was able to solve by subclassing RegisterView and setting no authentication_classes



```
from rest_auth.registration.views import RegisterView
...
class RegisterViewToken(RegisterView):
    authentication_classes = ()
```

on urls.py:
`url(r'^rest-auth/registration/', csrf_exempt(RegisterViewToken.as_view()), name='rest_register'),`

be aware that you also need to change this for other urls endpoints, like here:

https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/registration/urls.py

as linked by @woegjiub, I think that this endpoint also should not require csrf_token, or authentication_class whatsoever.

Hope I have helped someone :)

**Comment by shulcsm** [comment]
There should be a better way to solve this. Why isn't this default? There is no reason to have auth classes for public views, and csrf_exempt does nothing for cases if you are not using sessions.

**Comment by ranihorev** [comment]
@dudanogueira, first of all - thanks!
In addition, I believe that setting the authentication_classes to be () is enough, and there is no need to use the csrf_exempt

**Comment by Reyvel** [comment]
any update? In development phase, I need the browseable api, so I have to use both token and session auth. Though there's an easy workaround, it'll be nice to have an official fix.

**Comment by andreyshipilov** [comment]
Basically, using just that:
```
'rest_framework.authentication.BasicAuthentication',
'rest_framework.authentication.TokenAuthentication',
```
works.

**Comment by leogregianin** [comment]
> Basically, using just that:
> 
> ```
> 'rest_framework.authentication.BasicAuthentication',
> 'rest_framework.authentication.TokenAuthentication',
> ```
> 
> works.

I have access to a token authentication and the session browsable API.
Deleted SessionAuthentication and included BasicAuthentication.
Works for me.

**Comment by Jayesh-Mahato** [comment]
> Basically, using just that:
> 
> ```
> 'rest_framework.authentication.BasicAuthentication',
> 'rest_framework.authentication.TokenAuthentication',
> ```
> 
> works.

This worked for me too.
Deleted the SessionAuthentication and included BasicAuthentication.

**Comment by bhuwan55** [comment]
if you are doing it from postman try deleting the cookies. It worked for me.

**Comment by ronakiihglobal** [comment]
For me adding `@api_view(['POST'])` worked

**Comment by Dileep9999** [comment]
`from rest_framework.authentication import SessionAuthentication, BasicAuthentication 

class CsrfExemptSessionAuthentication(SessionAuthentication):

    def enforce_csrf(self, request):
        return  # To not perform the csrf check previously happening`


Now Replace authentication_classes SessionAuthentication with CsrfExemptSessionAuthentication

**Comment by ppadi-TPR** [comment]
> if you are doing it from postman try deleting the cookies. It worked for me.

This solution worked for me
