### ISSUE TITLE
allauth>=0.25.0 :   __init__() takes exactly 2 arguments (1 given) error

### ISSUE THREAD

**Issue by nvcken** [Tivix/django-rest-auth#195]
```
Internal Server Error: /rest-auth/facebook/
Traceback (most recent call last):
  File "/Users/mywork/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/mywork/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mywork/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/mywork/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/mywork/venv/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/Users/mywork/venv/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/mywork/venv/lib/python2.7/site-packages/rest_auth/views.py", line 50, in post
    self.serializer.is_valid(raise_exception=True)
  File "/Users/mywork/venv/lib/python2.7/site-packages/rest_framework/serializers.py", line 213, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/Users/mywork/venv/lib/python2.7/site-packages/rest_framework/serializers.py", line 410, in run_validation
    value = self.validate(value)
  File "/Users/mywork/venv/lib/python2.7/site-packages/rest_auth/registration/serializers.py", line 63, in validate
    adapter = adapter_class()
TypeError: __init__() takes exactly 2 arguments (1 given)
```
I just follow installation 

```
from allauth.socialaccount.providers.facebook.views import FacebookOAuth2Adapter
from rest_auth.registration.views import SocialLoginView

class FacebookLogin(SocialLoginView):
    adapter_class = FacebookOAuth2Adapter

urlpatterns = [
...
        url(r'^rest-auth/', include('rest_auth.urls')),
	url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
	url(r'^rest-auth/facebook/$', FacebookLogin.as_view(), name='fb_login'),

]
```

**Comment by 80steve** [comment]
FYI
https://github.com/pennersr/django-allauth/commit/2cb74f4c3471e3451783621d3bd54932bb06fb34 changes OAuth2Adapter to require a "request " object during initialization
#191 happens to fix that

**Comment by nvcken** [comment]
Thanks @80steve 
When I was stuck from this error, I tried to debug step by step but I got lost on :
```
adapter = adapter_class()
```
Then I debug step into, I get into here
```
def run_validation(self, data=empty):
        """
        We override the default `run_validation`, because the validation
        performed by validators and the `.validate()` method should
        be coerced into an error dictionary with a 'non_fields_error' key.
        """
        (is_empty_value, data) = self.validate_empty_values(data)
        if is_empty_value:
            return data

        value = self.to_internal_value(data)
        try:
            self.run_validators(value)
            value = self.validate(value)
```
Then, I still don't know how to find out where error caution.
I was get hard time to debug error. Could you please tell me what error happen here? ( see how to fix is really simple but understand it is not easy for me )

**Comment by nvcken** [comment]
plz merge this https://github.com/Tivix/django-rest-auth/pull/191

**Comment by juliandramirez** [comment]
pennersr/django-allauth@2cb74f4 changes OAuth2Adapter to require a "request " object during initialization introduces a bug:

A no argument initializer was lost when "request" was added as a parameter.
rest_auth.registration.serializers.SocialLoginSerializer expects a no attribute initializer for the adapter class.

My current fix is to have this in my code:

```python
class FacebookOAuth2AdapterFixed(FacebookOAuth2Adapter):
    def __init__(self):
        pass
        
class FacebookLogin(SocialLoginView):
    adapter_class = FacebookOAuth2AdapterFixed
```

**Comment by nvcken** [comment]
Thanks @juliandramirez :+1:

**Comment by Tritlo** [comment]
I am having the same issue, but my error message reads:

    TypeError at /rest-auth/facebook/
    __init__() missing 1 required positional argument: 'request'

**Comment by hhamalai** [comment]
this is a valid bug. workaround by @juliandramirez works like a charm.

**Comment by mariodev** [comment]
Thanks all for contributing and resolving this issue. #191 has been merged to master. A new version of DRA (0.8.0) will be up very shortly.

**Comment by Sshuichi** [comment]
Any idea whenthe 0.8.0 will be out ?

**Comment by omidraha** [comment]
Please update `django-rest-auth` on the [pypi](https://pypi.python.org/pypi/django-rest-auth) for this issue.

**Comment by flxfxp** [comment]
0.8.1 is on pypi.
