### ISSUE TITLE
TemplateResponseMixin error when loading pages.

### ISSUE THREAD

**Issue by chrisfranklin** [Tivix/django-rest-auth#20]
Whenever I try and load a page I receive the following error:

Internal Server Error: /rest-auth/registration/account-email-verification-sent/
Traceback (most recent call last):
  File "/Users/chrisfranklin/ng/coderdash/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/Users/chrisfranklin/ng/coderdash/env/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, _args, *_kwargs)
  File "/Users/chrisfranklin/ng/coderdash/env/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, _args, *_kwargs)
  File "/Users/chrisfranklin/ng/coderdash/env/lib/python2.7/site-packages/django/views/generic/base.py", line 155, in get
    return self.render_to_response(context)
  File "/Users/chrisfranklin/ng/coderdash/env/lib/python2.7/site-packages/django/views/generic/base.py", line 130, in render_to_response
    template=self.get_template_names(),
  File "/Users/chrisfranklin/ng/coderdash/env/lib/python2.7/site-packages/django/views/generic/base.py", line 142, in get_template_names
    "TemplateResponseMixin requires either a definition of "
ImproperlyConfigured: TemplateResponseMixin requires either a definition of 'template_name' or an implementation of 'get_template_names()'
[26/Oct/2014 13:48:13] "GET /rest-auth/registration/account-email-verification-sent/ HTTP/1.1" 500 111497

Any ideas what might be causing it?

**Comment by saptami2016** [comment]
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: [example.com] Please Confirm Your E-mail Address
From: webmaster@localhost
To: snehikajha12@gmail.com
Date: Mon, 25 Mar 2019 10:10:25 -0000
Message-ID: <155350862592.20663.15233324582014097343@CND8303S4C>

Hello from example.com!

You're receiving this e-mail because user snehika0 has given yours as an e-mail address to connect their account.

To confirm this is correct, go to http://127.0.0.1:8000/api/v1/rest-auth/registration/account-confirm-email/MTc:1h8MYj:WJQlIv2ESEkmM8wOoIxYrnSJbag/

Thank you from example.com!
example.com
-------------------------------------------------------------------------------
[25/Mar/2019 10:10:26] "POST /api/v1/rest-auth/registration/ HTTP/1.1" 201 7326
Internal Server Error: /api/v1/rest-auth/registration/account-confirm-email/MTc:1h8MYj:WJQlIv2ESEkmM8wOoIxYrnSJbag/
Traceback (most recent call last):
  File "/home/hp/.local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/hp/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/hp/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hp/.local/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/hp/.local/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/hp/.local/lib/python3.5/site-packages/django/views/generic/base.py", line 150, in get
    return self.render_to_response(context)
  File "/home/hp/.local/lib/python3.5/site-packages/django/views/generic/base.py", line 125, in render_to_response
    template=self.get_template_names(),
  File "/home/hp/.local/lib/python3.5/site-packages/django/views/generic/base.py", line 138, in get_template_names
    "TemplateResponseMixin requires either a definition of "
django.core.exceptions.ImproperlyConfigured: TemplateResponseMixin requires either a definition of 'template_name' or an implementation of 'get_template_names()'
[25/Mar/2019 10:10:45] "GET /api/v1/rest-auth/registration/account-confirm-email/MTc:1h8MYj:WJQlIv2ESEkmM8wOoIxYrnSJbag/ HTTP/1.1" 500 92330

**I am also getting same error but m unable to ressolve **
