### ISSUE TITLE
account_email_confim No Reverse Match

### ISSUE THREAD

**Issue by chubz** [Tivix/django-rest-auth#232]
Hi, I know this has been rehashed but this seems to persist and I cannot remove the error no matter how I reconfigure the urls:

my urls.py
```python
from allauth.account.views import confirm_email
urlpatterns = patterns('',
url(r'^api/v1/rest-auth/registration/account-confirm-email/(?P<key>[-/\w]+)/$', confirm_email, name='account_confirm_email'),
url(r'^api/v1/rest-auth/', include('rest_auth.urls')),
url(r'^api/v1/rest-auth/registration/', include('rest_auth.registration.urls')),
url(r'^api/v1/rest-auth/facebook/$', 'common.api.fb_login', name='fb_login'),
# url(r'^account/', include('allauth.urls')),
...
)
```
account_confirm_email is the first pattern I have no namespaces defined.
Also I've imported allauths view to override the empty/dummy TemplateView defined by django-rest-auth.
Still when I run a curl call on register endpoint api/v1/rest-auth/registration/ I have No reverse match error thrown.
This is what comes out of shell:
```python
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/borko/.virtualenvs/cco_apiauth/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/borko/.virtualenvs/cco_apiauth/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'account_confirm_email' with arguments '('Mzk:1bSNFh:JqL2-mnq0toOx6efgmLSjxh3A5M',)' and keyword arguments '{}' not found. 2 pattern(s) tried: ['api/v1/rest-auth/registration/account-confirm-email/(?P<key>\\w+)/$', 'api/v1/rest-auth/registration/account-confirm-email/(?P<key>[-/\\w]+)/$']
```

This recognizes two patterns since after hitting my override it hits the TemplateView still defined in django-rest-auth.

lib versions:
Django==1.8.14
djangorestframework==3.4.0
django-rest-auth==0.8.0
djangorestframework-jwt==1.8.0

Any advice on how to proceed here would be great.

**Comment by chubz** [comment]
I managed to hunt it down. the pattern in the docs should be updated to reflect newer django-allauth pattern for matching the hmac token to [-:\w]+ this way the faq leads to confusion with current pattern.

**Comment by chubz** [comment]
I've changed what I saw needed a change and added a line to docs for it 
you guys can check it here #233

**Comment by chubz** [comment]
@mariodev I'll close this issue since the pattern has been updated and the pr awaits you to close it.
