### ISSUE TITLE
rest_auth.registration email confirmation: "No module named 'user'"

### ISSUE THREAD

**Issue by mbaragiola** [Tivix/django-rest-auth#261]
Hello, I've set up and successfully ran Django 1.10.1, DRF 3.4.7, django-allauth 0.27.0 and django-rest-auth 0.8.1 (with JWT installed and enabled).

User registration is working fine, but email confirmation is not. When I register an user, it is created and then when trying to send the confirmation email, Django says that there is no module named 'user'. This happends at allauth/templates/account/email/email_confirmation_signup_message.txt error at line 1.

Is this a versioning problem? Am I doing something wrong? Thanks in advance.

**Comment by mariodev** [comment]
@mbaragiola Can you please provide the full traceback? Thanks

**Comment by mbaragiola** [comment]
Sure @mariodev , sorry for the delay:

Internal Server Error: /api/rest-auth/registration/
Traceback (most recent call last):
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/rest_framework/views.py", line 474, in dispatch
    response = self.handle_exception(exc)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/rest_framework/views.py", line 434, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/rest_framework/views.py", line 471, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/rest_framework/generics.py", line 191, in post
    return self.create(request, *args, **kwargs)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/rest_auth/registration/views.py", line 50, in create
    user = self.perform_create(serializer)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/rest_auth/registration/views.py", line 64, in perform_create
    None)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/allauth/account/utils.py", line 183, in complete_signup
    signal_kwargs=signal_kwargs)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/allauth/account/utils.py", line 146, in perform_login
    send_email_confirmation(request, user, signup=signup)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/allauth/account/utils.py", line 310, in send_email_confirmation
    signup=signup)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/allauth/account/models.py", line 62, in send_confirmation
    confirmation.send(request, signup=signup)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/allauth/account/models.py", line 172, in send
    get_adapter(request).send_confirmation_mail(request, self, signup)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/allauth/account/adapter.py", line 420, in send_confirmation_mail
    ctx)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/allauth/account/adapter.py", line 140, in send_mail
    msg = self.render_mail(template_prefix, email, context)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/allauth/account/adapter.py", line 119, in render_mail
    context).strip()
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/allauth/account/templatetags/account.py", line 17, in render
    display = user_display(user)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/allauth/account/utils.py", line 88, in user_display
    _user_display_callable = import_callable(f)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/allauth/utils.py", line 120, in import_callable
    ret = import_attribute(path_or_callable)
  File "/home/mib/workspace/turnateme/lib/python3.4/site-packages/allauth/utils.py", line 114, in import_attribute
    ret = getattr(importlib.import_module(pkg), attr)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'user'

**Comment by mariodev** [comment]
@mbaragiola Did you set up `ACCOUNT_USER_DISPLAY` setting? If so - remember that it needs to be a callable. By looking at the error it seems that it somehow returns a `user` string.

**Comment by mbaragiola** [comment]
@mariodev Thanks for replying. I had configured ACCOUNT_USER_DISPLAY to a string with 'user.get_full_name'. I've commented it out from settings.py and now it's working. So that's it.

Before closing this issue, what's the correct way to set it? I can't get it right, either from a string or importing the model.

**Comment by mariodev** [comment]
@mbaragiola In your case, the following line should work fine:
```
ACCOUNT_USER_DISPLAY = lambda user: user.get_full_name()
```
