### ISSUE TITLE
Add settings key to allow logging out on GET request, if allauth is not included.

### ISSUE THREAD

**Issue by maxim-kht** [Tivix/django-rest-auth#279]

**Comment by nirizr** [comment]
This is related to #237, as that's where I initially posted the following:

> This should be reopened, as `allauth` is still an implicit requirement.
See views.py line 98 (https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/views.py#L98).

> `allauth_settings` is assumed to exist, while it only does if `allauth` is installed.

> This poses somewhat of a design question (should the setting be duplicated? Should it be ignored when allauth is missing?).

Thanks!

**Comment by waveywhite** [comment]
I just ran into this issue. Just in case this is helpful here is the error report that occurs when you do a GET to logout:

`Internal Server Error: /rest-auth/logout/
Traceback (most recent call last):
  File ".../project/django/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File ".../project/django/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File ".../project/django/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File ".../project/django/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File ".../project/django/env/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File ".../project/django/env/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File ".../project/django/env/lib/python3.5/site-packages/rest_framework/views.py", line 477, in dispatch
    response = self.handle_exception(exc)
  File ".../project/django/env/lib/python3.5/site-packages/rest_framework/views.py", line 437, in handle_exception
    self.raise_uncaught_exception(exc)
  File ".../project/django/env/lib/python3.5/site-packages/rest_framework/views.py", line 474, in dispatch
    response = handler(request, *args, **kwargs)
  File ".../project/django/env/lib/python3.5/site-packages/rest_auth/views.py", line 103, in get
    response = self.handle_exception(exc)
  File ".../project/django/env/lib/python3.5/site-packages/rest_framework/views.py", line 437, in handle_exception
    self.raise_uncaught_exception(exc)
  File ".../project/django/env/lib/python3.5/site-packages/rest_auth/views.py", line 98, in get
    if allauth_settings.LOGOUT_ON_GET:
NameError: name 'allauth_settings' is not defined`

**Comment by flesser** [comment]
I ran into the same issue using the [recommended basic install](https://django-rest-auth.readthedocs.io/en/latest/installation.html) without the optional Registration or Social sections.

I don't think the GET endpoint should be available by default (i.e. part of `rest_auth.urls`) as long as it depends on `allauth_settings`.

**Comment by maxim-kht** [comment]
Logout on GET is not recommended setting, since GET request should not alter internal state of the system and might cause unexpected behavior because URL prefetching in browser, etc. It is advisable to only use POST for logout request. More info: 
+ http://django-allauth.readthedocs.io/en/latest/views.html#logout
+ http://stackoverflow.com/questions/3521290/logout-get-or-post

But, since allauth has this setting, I am keeping it.. although I added the note in the docs saying that it's not recommended and link to allauth docs explaining why.
