### ISSUE TITLE
Demo project setup fails with Django-2.0

### ISSUE THREAD

**Issue by mr-kojo** [Tivix/django-rest-auth#395]
Setting up the demo project [as described in the docs](http://django-rest-auth.readthedocs.io/en/latest/demo.html) works perfectly fine with Django-1.11 but it fails with Django-2.0.

```
>>>python manage.py migrate --settings=demo.settings --noinput
Traceback (most recent call last):
  File "/tmp/django-rest-auth/demo/env/lib/python3.4/site-packages/rest_framework/compat.py", line 27, in <module>
    from django.urls import (
ImportError: cannot import name 'RegexURLPattern'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/tmp/django-rest-auth/demo/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/tmp/django-rest-auth/demo/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/tmp/django-rest-auth/demo/env/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/tmp/django-rest-auth/demo/env/lib/python3.4/site-packages/django/core/management/base.py", line 332, in execute
    self.check()
  File "/tmp/django-rest-auth/demo/env/lib/python3.4/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/tmp/django-rest-auth/demo/env/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 58, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/tmp/django-rest-auth/demo/env/lib/python3.4/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/tmp/django-rest-auth/demo/env/lib/python3.4/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/tmp/django-rest-auth/demo/env/lib/python3.4/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/tmp/django-rest-auth/demo/env/lib/python3.4/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/tmp/django-rest-auth/demo/env/lib/python3.4/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tmp/django-rest-auth/demo/env/lib/python3.4/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/tmp/django-rest-auth/demo/env/lib/python3.4/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tmp/django-rest-auth/demo/env/lib/python3.4/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/tmp/django-rest-auth/demo/env/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/tmp/django-rest-auth/demo/demo/urls.py", line 5, in <module>
    from rest_framework_swagger.views import get_swagger_view
  File "/tmp/django-rest-auth/demo/env/lib/python3.4/site-packages/rest_framework_swagger/views.py", line 1, in <module>
    from rest_framework import exceptions
  File "/tmp/django-rest-auth/demo/env/lib/python3.4/site-packages/rest_framework/exceptions.py", line 17, in <module>
    from rest_framework.utils.serializer_helpers import ReturnDict, ReturnList
  File "/tmp/django-rest-auth/demo/env/lib/python3.4/site-packages/rest_framework/utils/serializer_helpers.py", line 8, in <module>
    from rest_framework.compat import unicode_to_repr
  File "/tmp/django-rest-auth/demo/env/lib/python3.4/site-packages/rest_framework/compat.py", line 31, in <module>
    from django.core.urlresolvers import (  # Will be removed in Django 2.0
ImportError: No module named 'django.core.urlresolvers'
```

**Comment by maxim-kht** [comment]
Hi @mr-kojo the error is being thrown in Django REST Framework - upgrading djangorestframework to 3.7.0 will fix it. 

We will update requirements.txt in demo project.
