### ISSUE TITLE
ImportError: No module named core.serializers

### ISSUE THREAD

**Issue by andreyshipilov** [Tivix/django-rest-auth#429]
Basically I get this error from the issue title when adding this to the `urls.py`:
```
url(r'^rest-api/auth/registration/', include('rest_auth.registration.urls')),
```
This is the traceback:
```
Traceback (most recent call last):
  File "/Users/a/Projects/project/venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Users/a/Projects/project/venv/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/Users/a/Projects/project/venv/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/a/Projects/project/venv/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/a/Projects/project/venv/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/a/Projects/project/venv/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/Users/a/Projects/project/venv/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/Users/a/Projects/project/venv/lib/python2.7/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/Users/a/Projects/project/venv/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/a/Projects/project/venv/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/a/Projects/project/venv/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/a/Projects/project/venv/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/a/Projects/project/project_app_django/project_app/urls.py", line 49, in <module>
    url(r'^rest-api/auth/registration/', include('rest_auth.registration.urls')),
  File "/Users/a/Projects/project/venv/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/a/Projects/project/venv/lib/python2.7/site-packages/rest_auth/registration/urls.py", line 4, in <module>
    from .views import RegisterView, VerifyEmailView
  File "/Users/a/Projects/project/venv/lib/python2.7/site-packages/rest_auth/registration/views.py", line 32, in <module>
    from .app_settings import RegisterSerializer, register_permission_classes
  File "/Users/a/Projects/project/venv/lib/python2.7/site-packages/rest_auth/registration/app_settings.py", line 12, in <module>
    serializers.get('REGISTER_SERIALIZER', DefaultRegisterSerializer))
  File "/Users/a/Projects/project/venv/lib/python2.7/site-packages/rest_auth/utils.py", line 11, in import_callable
    return getattr(import_module(package), attr)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named core.serializers
```
This is `urls.py`:
```
api_router = routers.DefaultRouter()
api_router.register(r'cities', app.viewsets.CitiesViewSet)

urlpatterns += [
    # API URLs
    url(r'^rest-api/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^rest-api/', include(api_router.urls)),

    # Rest auth.
    url(r'^rest-api/auth/', include('rest_auth.urls')),
    url(r'^rest-api/auth/registration/', include('rest_auth.registration.urls')),

    # Allauth
    url(r'^account/', include('allauth.urls')),
]
```
Installed apps:
```
INSTALLED_APPS = (
    'crispy_forms',
    'compressor',
    'typogrify',
    'meta',
    'any_imagefield',
    'django_countries',
    'sorl.thumbnail',
    'clear_cache',
    'annoying',
    'markdown_deux',
    'django_filters',

    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_filters',
    'rest_auth',

    'allauth',
    'allauth.account',
    'rest_auth.registration',
    'allauth.socialaccount.providers.instagram',
    'allauth.socialaccount.providers.twitter',
)
```
Any thoughts? If I comment the `rest-api/auth/registration/` in the `urls.py` there are no errors of course.

**Comment by mariodev** [comment]
Closing, since it's not DRA specific issue. Please post this question on [stackoverflow](https://stackoverflow.com/) instead.

**Comment by andreyshipilov** [comment]
@mariodev So `rest_auth.registration.urls` is not related to DRA? Understood...

**Comment by mariodev** [comment]
@andreyshipilov Yes, it is related, but it's not a DRA bug.

**Comment by andreyshipilov** [comment]
Can you please explain. I don't get it how this:
```
  File "/Users/a/Projects/project/venv/lib/python2.7/site-packages/rest_auth/registration/urls.py", line 4, in <module>
    from .views import RegisterView, VerifyEmailView
  File "/Users/a/Projects/project/venv/lib/python2.7/site-packages/rest_auth/registration/views.py", line 32, in <module>
    from .app_settings import RegisterSerializer, register_permission_classes
  File "/Users/a/Projects/project/venv/lib/python2.7/site-packages/rest_auth/registration/app_settings.py", line 12, in <module>
    serializers.get('REGISTER_SERIALIZER', DefaultRegisterSerializer))
  File "/Users/a/Projects/project/venv/lib/python2.7/site-packages/rest_auth/utils.py", line 11, in import_callable
    return getattr(import_module(package), attr)
```
Is not DRA related code that cause it to bug out.

**Comment by mariodev** [comment]
Seems like your `REGISTER_SERIALIZER` setting is pointing to `core.serializers` module, which probably doesn't exist.

**Comment by zaheerkzz** [comment]
https://djoser.readthedocs.io/en/latest/settings.html
check this link:
DJOSER = {
    'SERIALIZERS': {
        'user_create':  'djoser.serializers.UserCreateSerializer'
    }
}

solved issue.
