### ISSUE TITLE
Cannot Login (allauth.account.models.EmailAddress.DoesNotExist)

### ISSUE THREAD

**Issue by yongwoon** [Tivix/django-rest-auth#473]
I set as blew, I could user registration, verify-mail. But when I try to login, occur the error.
How to solve the problem? 

* version
  * django 2.1.2
  * django-allauth 0.38.0
  * django-rest-auth 0.9.3
* urls
```
urlpatterns = [
    path('', include('rest_auth.urls')),
    path('registration/account-email-verification-sent/', django_rest_auth_null, name='account_email_verification_sent'),
    path('registration/', include('rest_auth.registration.urls')),
]
```

* settings
```
# Rest-framework
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    )
}

SITE_ID = 1
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[test blog]"
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = False
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_UNIQUE_EMAIL = True
AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)


REST_AUTH_SERIALIZERS = {
    'USER_DETAILS_SERIALIZER': 'users.api.serializers.UserSerializer'
}
```

### ERROR
```
nternal Server Error: /api/accounts/login/
Traceback (most recent call last):
  File "/blog_env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/blog_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/blog_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/blog_env/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/blog_env/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/blog_env/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/blog_env/lib/python3.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/blog_env/lib/python3.7/site-packages/rest_auth/views.py", line 49, in dispatch
    return super(LoginView, self).dispatch(*args, **kwargs)
  File "/blog_env/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/blog_env/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/blog_env/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/blog_env/lib/python3.7/site-packages/rest_auth/views.py", line 93, in post
    self.serializer.is_valid(raise_exception=True)
  File "/blog_env/lib/python3.7/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/blog_env/lib/python3.7/site-packages/rest_framework/serializers.py", line 437, in run_validation
    value = self.validate(value)
  File "/blog_env/lib/python3.7/site-packages/rest_auth/serializers.py", line 105, in validate
    email_address = user.emailaddress_set.get(email=user.email)
  File "/blog_env/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/blog_env/lib/python3.7/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
allauth.account.models.EmailAddress.DoesNotExist: EmailAddress matching query does not exist.
[29/Oct/2018 03:59:35] "POST /api/accounts/login/ HTTP/1.1" 500 18654
[29/Oct/2018 04:41:41] "GET /admin/ HTTP/1.1" 200 7533
```

**Comment by yongwoon** [comment]
Sorry, just my data missing
