### ISSUE TITLE
REST_AUTH_REGISTER_SERIALIZERS completely ignored

### ISSUE THREAD

**Issue by sudomann** [Tivix/django-rest-auth#529]
In my `settings.py` I have set:

```
REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'users.serializers.UserRegisterSerializer',
}
```

where:
-  `users` is my Django app containing my custom user model
- `serializers` is a python file in which
  - `UserRegisterSerializer` is defined

This is in accordance with the [docs](https://django-rest-auth.readthedocs.io/en/0.9.4/configuration.html):

> REST_AUTH_REGISTER_SERIALIZERS
> 
> You can define your custom serializers for registration endpoint. Possible key values:
> 
> REGISTER_SERIALIZER - serializer class in rest_auth.registration.views.RegisterView, default value rest_auth.registration.serializers.RegisterSerializer

`django-rest-auth` still tries to use its default `RegisterSerializer` which causes Django to crash, as my `CustomUser` model does not have a username field (why I need a custom REGISTER_SERIALIZER in the first place).

```
$ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Traceback (most recent call last):
  File "/home/sudomann/repos/divvy-env/lib/python3.6/site-packages/django/db/models/options.py", line 565, in get_field
    return self.fields_map[field_name]
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/sudomann/repos/divvy-env/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/sudomann/repos/divvy-env/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sudomann/repos/divvy-env/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/sudomann/repos/divvy-env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "/home/sudomann/repos/divvy-env/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/sudomann/repos/divvy-env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 95, in handle
    self.run(**options)
  File "/home/sudomann/repos/divvy-env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "/home/sudomann/repos/divvy-env/lib/python3.6/site-packages/django/utils/autoreload.py", line 579, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "/home/sudomann/repos/divvy-env/lib/python3.6/site-packages/django/utils/autoreload.py", line 564, in start_django
    reloader.run(django_main_thread)
  File "/home/sudomann/repos/divvy-env/lib/python3.6/site-packages/django/utils/autoreload.py", line 272, in run
    get_resolver().urlconf_module
  File "/home/sudomann/repos/divvy-env/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/sudomann/repos/divvy-env/lib/python3.6/site-packages/django/urls/resolvers.py", line 564, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/sudomann/repos/divvy-env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sudomann/repos/divvy-env/divvy/django/divvy/urls.py", line 22, in <module>
    path('api/', include('api.urls')),
  File "/home/sudomann/repos/divvy-env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/sudomann/repos/divvy-env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sudomann/repos/divvy-env/divvy/django/api/urls.py", line 6, in <module>
    path('rest-auth/registration/', include('rest_auth.registration.urls')),
  File "/home/sudomann/repos/divvy-env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/sudomann/repos/divvy-env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sudomann/repos/divvy-env/lib/python3.6/site-packages/rest_auth/registration/urls.py", line 4, in <module>
    from .views import RegisterView, VerifyEmailView
  File "/home/sudomann/repos/divvy-env/lib/python3.6/site-packages/rest_auth/registration/views.py", line 26, in <module>
    from rest_auth.registration.serializers import (VerifyEmailSerializer,
  File "/home/sudomann/repos/divvy-env/lib/python3.6/site-packages/rest_auth/registration/serializers.py", line 166, in <module>
    class RegisterSerializer(serializers.Serializer):
  File "/home/sudomann/repos/divvy-env/lib/python3.6/site-packages/rest_auth/registration/serializers.py", line 168, in RegisterSerializer
    max_length=get_username_max_length(),
  File "/home/sudomann/repos/divvy-env/lib/python3.6/site-packages/allauth/utils.py", line 68, in get_username_max_length
    max_length = User._meta.get_field(USER_MODEL_USERNAME_FIELD).max_length
  File "/home/sudomann/repos/divvy-env/lib/python3.6/site-packages/django/db/models/options.py", line 567, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: CustomUser has no field named 'username'
```

**Comment by rpkilby** [comment]
The issue is arguably an implementation fault in django-allauth. Their `get_username_max_length` utility relies on their `ACCOUNT_USER_MODEL_USERNAME_FIELD` setting, instead of inspecting the [`USERNAME_FIELD`](https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#django.contrib.auth.models.CustomUser.USERNAME_FIELD) of the project's `AUTH_USER_MODEL`. 

So, you should be able to fix this by setting `ACCOUNT_USER_MODEL_USERNAME_FIELD` to your custom user model's `USERNAME_FIELD`. In general, if you're providing a custom user model, you should read their [custom user model docs](https://django-allauth.readthedocs.io/en/latest/advanced.html?highlight=ACCOUNT_USER_MODEL_USERNAME_FIELD#custom-user-models).

**Comment by sudomann** [comment]
Goodness, I can't believe I didn't spot this. 4 hours wasted smh. I actually got so frustrated I branched off in my project to use djoser instead. Worked pretty well. I simultaneously develop using both in their respective branches and see which one has me banging my head the least.

Thanks for the pointer.
