### ISSUE TITLE
No module found

### ISSUE THREAD

**Issue by SzateX** [Tivix/django-rest-auth#627]
Hi, I have problem with installing django-rest-auth with Github and JWT.

`(KoloRESTApi) E:\#PROJEKTY\#PROGRAMOWANIE\KoloRESTApi>python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "E:\#VENV\KoloRESTApi\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "E:\#VENV\KoloRESTApi\lib\site-packages\django\core\management\__init__.py", line 347, in execute
    django.setup()
  File "E:\#VENV\KoloRESTApi\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "E:\#VENV\KoloRESTApi\lib\site-packages\django\apps\registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "E:\#VENV\KoloRESTApi\lib\site-packages\django\apps\config.py", line 116, in create
    mod = import_module(mod_path)
  File "C:\Users\Szatku\AppData\Local\Programs\Python\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'allauth.socialaccount.providers.githubrest_auth'
`

I'm following the instruction in docs, and don't know what happens when I'm trying to migrate. 

Here you can see settings.py file: [https://github.com/skni-kod/SKNIKodBackEndServer/blob/master/KoloRESTApi/settings.py](url)

**Comment by SzateX** [comment]
Repaired problem - simply missing ',' in list of Installed Apps
