### ISSUE TITLE
ImportError: cannot import name 'url' from 'django.conf.urls'

### ISSUE THREAD

**Issue by UsamaHaide0786** [Tivix/django-rest-auth#659]
(env_universal) usama@Usamas-MacBook-Pro DRF_test % python manage.py makemigrations
Traceback (most recent call last):
  File "/Users/usama/Desktop/projects/DRF_test/manage.py", line 22, in <module>
    main()
  File "/Users/usama/Desktop/projects/DRF_test/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/usama/Desktop/projects/env_universal/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/Users/usama/Desktop/projects/env_universal/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/usama/Desktop/projects/env_universal/lib/python3.9/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/usama/Desktop/projects/env_universal/lib/python3.9/site-packages/django/core/management/base.py", line 455, in execute
    self.check()
  File "/Users/usama/Desktop/projects/env_universal/lib/python3.9/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/Users/usama/Desktop/projects/env_universal/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/usama/Desktop/projects/env_universal/lib/python3.9/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/usama/Desktop/projects/env_universal/lib/python3.9/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/Users/usama/Desktop/projects/env_universal/lib/python3.9/site-packages/django/urls/resolvers.py", line 480, in check
    for pattern in self.url_patterns:
  File "/Users/usama/Desktop/projects/env_universal/lib/python3.9/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/usama/Desktop/projects/env_universal/lib/python3.9/site-packages/django/urls/resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/usama/Desktop/projects/env_universal/lib/python3.9/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/usama/Desktop/projects/env_universal/lib/python3.9/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/usama/Desktop/projects/DRF_test/buzzshare/urls.py", line 8, in <module>
    path('rest-auth/', include('rest_auth.urls')),
  File "/Users/usama/Desktop/projects/env_universal/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/usama/Desktop/projects/env_universal/lib/python3.9/site-packages/rest_auth/urls.py", line 1, in <module>
    from django.conf.urls import url
ImportError: cannot import name 'url' from 'django.conf.urls' (/Users/usama/Desktop/projects/env_universal/lib/python3.9/site-packages/django/conf/urls/__init__.py)
(env_universal) usama@Usamas-MacBook-Pro DRF_test % pip install django-rest-auth

Is it not compatible with django 4

**Comment by AnthonyAniobi** [comment]
This problem has been solved [here](https://github.com/Tivix/django-rest-auth/issues/650#issuecomment-1030731806)
try using 
`pip install django-rest-auth-forked`

**Comment by mooktar** [comment]
Hi!
This happen because url in django.conf.urls is deprecated in Django 4.0.x
To fix it import re_path as url from django.urls

**Comment by Ubeydu** [comment]
This here will fix your issue:

![Screen Shot 2023-03-12 at 23 07 32](https://user-images.githubusercontent.com/64747345/224570534-fb1a5d3a-72f7-4548-a35f-1fa13af5d795.png)

**Comment by vardhans07** [comment]
> BenBrostoff

even install pip but still this error  occure

rom django.conf.urls import url, include
ImportError: cannot import name 'url' from 'django.conf.urls'

**Comment by vardhans07** [comment]
> This here will fix your issue:
> 
> ![Screen Shot 2023-03-12 at 23 07 32](https://user-images.githubusercontent.com/64747345/224570534-fb1a5d3a-72f7-4548-a35f-1fa13af5d795.png)

tried this way but still not working .

**Comment by franzferdinnand** [comment]
still not working, same if use path, or re_path
it appears only if using social-auth-app-django

<img width="742" alt="Знімок екрана 2023-09-03 о 09 38 51" src="https://github.com/Tivix/django-rest-auth/assets/110455433/3a6eebf9-cf11-415c-8ad4-a966e7d9b288">

**Comment by pritamaudviklabs** [comment]
Switch to dj-rest-auth
django-rest-auth is deprecated. Replace it with the actively maintained dj-rest-auth library
link : https://dj-rest-auth.readthedocs.io/en/latest/installation.html

**Comment by pritamn11** [comment]
Switch to dj-rest-auth 
django-rest-auth is deprecated. Replace it with the actively maintained dj-rest-auth
link : https://dj-rest-auth.readthedocs.io/en/latest/installation.html
