### ISSUE TITLE
AttributeError: 'User' object has no attribute 'backend'

### ISSUE THREAD

**Issue by philippeluickx** [Tivix/django-rest-auth#78]
Not sure where this suddenly comes from...

AttributeError: 'User' object has no attribute 'backend'

rest_auth/views.py", line 54, in login
    login(self.request, self.user)

Got pointed to these docs:
https://docs.djangoproject.com/en/1.8/topics/auth/default/#django.contrib.auth.login

What baffles me is that everything was working nicely before and I have no clue what I changed to get this message...

**Comment by NabeelValapra** [comment]
Do you have below configuration in your settings?

AUTHENTICATION_BACKENDS = (
    ...
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
    ...
)

**Comment by philippeluickx** [comment]
Yup, I got

    AUTHENTICATION_BACKENDS = (
        'django.contrib.auth.backends.ModelBackend',
        'allauth.account.auth_backends.AuthenticationBackend',
    )

**Comment by philippeluickx** [comment]
Installed it in a clean environment and not able to reproduce. Will close and reopen if this happens again.

**Comment by SakuradaJun** [comment]
I'm using version django-allauth==0.21.0 from pypi
I catch such an error from time to time.
Full stack trace:

```Python

ERROR 2015-07-06 22:52:17,694 base 10 140595800213312 Internal Server Error: /rest-auth/facebook/
  File "/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/rest_framework/views.py", line 456, in dispatch
    return self.dispatch(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/rest_framework/views.py", line 453, in dispatch
    response = self.handle_exception(exc)
  File "/app/.heroku/python/lib/python2.7/site-packages/rest_auth/views.py", line 76, in post
    response = handler(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/rest_auth/views.py", line 55, in login
    self.login()
    login(self.request, self.user)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 112, in login
    request.session[BACKEND_SESSION_KEY] = user.backend
AttributeError: 'User' object has no attribute 'backend'

```

**Comment by tezro** [comment]
Just got the same error. http://pastebin.com/4urVgAkk

Got AUTHENTICATION_BACKENDS set up properly too.

**Comment by SakuradaJun** [comment]
@tezro 
Recently, I also faced with this problem. I'm using this fork https://github.com/philippeluickx/django-rest-auth
I think it may be because when saving new user of its username (as I understand it takes from the email, but not always) already exists in the database and this leads to that the user object is not saved and the user cannot be authenticated.

**Comment by philippeluickx** [comment]
@SakuradaJun Normally the methods from allauth check if the username exists already and adds a digit to it if so. E.g. if "johndoe@gmail.com" has username "johndoe" then a new user registering with email "johndoe@yahoo.com" will get username "johndoe2".

Are you folks able to reproduce this every time?

**Comment by tezro** [comment]
@philippeluickx yeah man, the usual register process through REST /api/register/ works fine although the Facebook one fails. Is it possible I am missing something I need to do for the allauth and rest-auth work together and have the user's email as a primary registration credential and not the username?

**Comment by tezro** [comment]
Just tried it again on a clean virtualenv setup, clean database. Still the same error.

**Comment by philippeluickx** [comment]
How are your settings?

On my side these work, albeit they are probably not perfect...

ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = False
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_USERNAME_REQUIRED = False
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = False
SOCIALACCOUNT_EMAIL_VERIFICATION = False
ACCOUNT_SIGNUP_PASSWORD_VERIFICATION = False

**Comment by SakuradaJun** [comment]
I think I got it.
At this line 
https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/helpers.py#L29
it can return `HttpResponseRedirect`, it's returns in case with `auto_signup` is `False`
For example if email is not unqie:
https://github.com/pennersr/django-allauth/blob/9e5b85f30b411ad7aedba3985ae486e803657189/allauth/socialaccount/adapter.py#L128

I dare say that is a weird and awful pieces of code.

But at this line we not handle it.
https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/registration/serializers.py#L38

Also not unique username not handling correctly
https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/helpers.py#L39

My settings:
```Python
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_MIN_LENGTH = 2
```
At now I did a quick and simple patches for my project, but do not think I can do pull request for fix it that would be good enough.

**Comment by tezro** [comment]
@philippeluickx hey man, I'll try your settings now. Can you please check which one is the correct here.

```
ACCOUNT_EMAIL_VERIFICATION = False
ACCOUNT_EMAIL_VERIFICATION = "none"
```

**Comment by tezro** [comment]
@SakuradaJun hey, I'm trying the fork that you suggested, although have one problem now.

The url for authenticating with Facebook "/rest-auth/facebook/" expects Access token and Code. What's the Code in here and where does it come from? The browseable API expects both values and not letting to pass only Access token. Even though in the code it is set to required=False https://github.com/philippeluickx/django-rest-auth/blob/master/rest_auth/registration/serializers.py#L15

Can you help please.

**Comment by philippeluickx** [comment]
@tezro good catch on those settings.
From the docs http://django-allauth.readthedocs.org/en/latest/configuration.html

ACCOUNT_EMAIL_VERIFICATION (=”optional”)
Determines the e-mail verification method during signup – choose one of “mandatory”, “optional”, or “none”. When set to “mandatory” the user is blocked from logging in until the email address is verified. Choose “optional” or “none” to allow logins with an unverified e-mail address. In case of “optional”, the e-mail verification mail is still sent, whereas in case of “none” no e-mail verification mails are sent.

So "none" is the correct setting.

**Comment by philippeluickx** [comment]
@tezro @SakuradaJun The code in that fork could be a bit buggy... allauth is quite a complex beast and the rest-auth lib is quite young so some features missing (such as auth code).
If there is enough interest in that branch, I could clean up the code and fix some of the bugs (feel free to submit issues or even better a PR). When quality is good enough, I can submit a new PR to the original lib.

**Comment by tezro** [comment]
@philippeluickx thanks for help. I think I narrowed the problem down to the fact that the username is not created properly when I want to use **email** only. Submitted this ticket to allauth https://github.com/pennersr/django-allauth/issues/1022

If that's ok, can you please check it, cause to me it seems I could be fiddling the settings too much, or not using them properly.

**Comment by philippeluickx** [comment]
According to these docs:

https://github.com/pennersr/django-allauth/blob/9e5b85f30b411ad7aedba3985ae486e803657189/docs/advanced.rst#custom-user-models

Seems to me that this setting is maybe more in line when you have a custom user model? That is what I am doing in my case, so my user model does not have a username field...
In case you are using the standard user model, you would have to change your settings...


Someone with a similar issue, might shed some light:

https://github.com/pennersr/django-allauth/issues/882

**Comment by tezro** [comment]
@philippeluickx I am using a custom user model, but extending it with the User byt OneToOne field.

```
class Profile(models.Model):
    user = AutoOneToOneField(User, primary_key=True)
    country = CountryField()
```

In that case, should I use ACCOUNT_USER_MODEL_USERNAME_FIELD=None right?

**Comment by philippeluickx** [comment]
https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#specifying-a-custom-user-model

It is better to inherit from AbstractBaseUser
If you read a bit more about it, inheriting from User is generally discouraged.

**Comment by tezro** [comment]
Oh, I though that was the preferred method. In that case, yep, will red. Thanks for help again.

**Comment by philippeluickx** [comment]
Good luck, keep us updated on if it works in the end!

**Comment by hhamalai** [comment]
Thumbs up for this. Just encountered the same issue of backend attribute missing with FB logins.

**Comment by deecodameeko** [comment]
Set ACCOUNT_SIGNUP_FORM_CLASS for all auth customs forms and not

    ACCOUNT_FORMS = {
       'signup': 'path.to.custom.SignupForm'
    }

Rest auth doesn't use the custom form as designed with allauth. It doesn't hook into allauth validation and that's why usernames are blank when setting to register with an email instead of a username.

**Comment by tezro** [comment]
@philippeluickx hey man, I tried creating a custom model by subclassing AbstractUser (an AbstractBaseUser). I extended the settings with this:
```
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'

SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = False
SOCIALACCOUNT_EMAIL_VERIFICATION = False
SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'SCOPE': ['email', 'public_profile'],
        'VERIFIED_EMAIL': True,
        'VERSION': 'v2.4'
    }
}

AUTH_USER_MODEL = 'users.CustomUser'
```
And even now it throws:
```
'CustomUser' object has no attribute 'backend'
```
And still creates a user without username/email.

Even if the extended permissions are a set for providing an email in the Facebook App settings...

<img width="596" alt="screen shot 2015-07-14 at 01 25 05" src="https://cloud.githubusercontent.com/assets/188876/8654067/36d39aba-29c7-11e5-8b7e-b3594df30df2.png">

Ok, now I'm lost. Need help.

**Comment by tezro** [comment]
Well, I've tested it as much as I can and:

* Through /accounts/facebook/login/ the *regular Django allauth process* — the user is created from Facebook, all good.
* Through /rest-api/facebook/ (*handled by FacebookLogin.as_view()* from the docs) — the user is created (POSTing a valid Facebook access key) with an empty email and username even though the SOCIALACCOUNT_PROVIDERS has the SCOPE for email. The process is followed by throwing an error "CustomUser object has no attribute backend" (where CustomUser is the custom auth user model). On any next call to the same url (still POSTing the same valid Facebook access key) no errors occur.

Am I doing it wrong again? :)

**Comment by tezro** [comment]
@deecodameeko hey man, do you have an example for ACCOUNT_SIGNUP_FORM_CLASS if I use an email for registrations? Are signup and login form classes different in that case and I need to supply both?

**Comment by philippeluickx** [comment]
Reopening as this seems to be an active issue... Will try and find time tomorrow to investigate

**Comment by philippeluickx** [comment]
https://github.com/pennersr/django-allauth/blob/9e5b85f30b411ad7aedba3985ae486e803657189/allauth/socialaccount/providers/base.py#L50

Leads to

https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/adapter.py#L71

Would be good breakpoints to debug and see what is going on there...


Just a quick check: are you folks using django 1.8? Are you using a recent version of allauth?

**Comment by tezro** [comment]
@philippeluickx Django 1.7.8, Python 2.7.10.

**Comment by philippeluickx** [comment]
@tezro I have the feeling that the cause is the empty email returned. The username is deducted from the email address (if no username is given).
Could you check what request is sent to Facebook and what the response is you get back?

**Comment by philippeluickx** [comment]
@tezro It is a bit hard for me to reproduce this, I am getting first and last names, email from Facebook and thus also a username.
Could you try without having SOCIALACCOUNT_PROVIDERS defined? I left those on default.
Also for the Facebook settings, I never had to touch the permissions.

**Comment by tezro** [comment]
@philippeluickx yeah man. The response from Facebook is first and last name. The email is not granted by default, but I suppose that shouldn't affect the user creation. I was doing it without and with SOCIALACCOUNT_PROVIDERS so, damn...

Can you by any chance post "pip freeze" here?

**Comment by philippeluickx** [comment]
This is what I got for django and allauth-related:

Django==1.8.2
django-allauth==0.19.1
-e git://github.com/philippeluickx/django-rest-auth.git@1371eb932e415f6326fd0eb3a4b6f4c15e690c98#egg=django_rest_auth-master
djangorestframework==3.1.2

When I go to status and review tab for Facebook settings, I have email as default. Did you activate your app?:

Approved Items
LOGIN PERMISSIONS
email
Provides access to the person's primary email address. This permission is approved by default.
public_profile
Provides access to a person's basic information, including first name, last name, profile picture, gender and age range. This permission is approved by default.
user_friends
Provides access to a person's list of friends that also use your app. This permission is approved by default.

**Comment by tezro** [comment]
Yes, the app is activated. What's the "status and review" tab man?

**Comment by philippeluickx** [comment]
Facebook developer thingy:
![statusreview](https://cloud.githubusercontent.com/assets/836866/8672239/34bb3bac-2a35-11e5-8f55-fdec9d67a110.png)

**Comment by tezro** [comment]
Ah, I get it. Nope, the app is still in dev mode.

**Comment by philippeluickx** [comment]
Any impact when marked to live? It would surprise me, as I have a dev app in FB as well which is not submitted, but still seems to work.
Do you have the same texts below, especially that email is approved by default?

**Comment by smilledge** [comment]
Also having this issue with Facebook login. User's are getting created without a username or email. 

The `AttributeError: 'User' object has no attribute 'backend'` looks to be caused by not receiving an email from Facebook, so setting `SOCIALACCOUNT_EMAIL_REQUIRED` to `False` is fixing this, but still not receiving the user's data from Facebook. 

The access token, scopes, api version and Facebook app settings are all correct.

**Comment by philippeluickx** [comment]
Cool, looks like the root cause is FB update > allauth issue. Closing this here again, to be followed up at https://github.com/pennersr/django-allauth/issues/1030

**Comment by citizen-stig** [comment]
I think this issue should be reopened.
The reason is following: allauth allows to add email field on signup form after social login, provider doesn't provide email. It is very convenient for instance, when you have a email required, but want to login users via Twitter. 
And allauth actually pass information about additional fields indirectly to the rest_auth, when rest_auth calls ```complete_social_login``` (rest_auth.registration.serializers.py:38). This function returns the redirect response to the 'signup_form'

I also think that ```SocialLoginSerializer``` is kinda complicated. for instance if I want to something similar to adding a token to account, is it's done on rest_auth.registration.serializers.py:37 I need completely override the validate method. Maybe it will be better to split this method into two methods, one prepares social_login object and the other one completes the rest. What do you think?

**Comment by philippeluickx** [comment]
Definitely open for improvement. The challenge is that allauth is not as modular as it could be, making it more difficult to have a REST wrapper around it without becoming redundant. Reopening.

**Comment by citizen-stig** [comment]
Please take a look at my pull request. 

The possible solution for cases, when you have an mandatory email field is just subclass ```SocialLoginSerializer```` and use this serializer in the social login view

    # serializers.py
    class EmailSocialLoginSerializer(SocialLoginSerializer):
        email = serializers.EmailField(required=True)
    
        def get_social_login(self, adapter, app, token, response):
            social_login = super(EmailSocialLoginSerializer, self).get_social_login(adapter, app, token, response)
            social_login.email = self.data['email']
            return social_login

**Comment by rggibson** [comment]
I'm experiencing the same, original error.  I'm able to reproduce it by simply registering an account through email/password, and then later trying to login with Facebook where the email I registered with matches my Facebook email.  When I check the Users on the admin page, upon Facebook login, a new user is (incorrectly) registered with a duplicate email address and a blank username.  Here are my settings:

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

# allauth settings
ACCOUNT_PASSWORD_MIN_LENGTH = 4
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = '/login'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = True
SOCIALACCOUNT_STORE_TOKENS = False

I'm pretty sure the problem stems from rest-auth not catching the fact that we should be skipping the auto-signup step after a duplicate email is detected by allauth, as others in this issue thread have suggested.

**Comment by philippeluickx** [comment]
Just as a tip, in my case I am using a pure REST interface with tokens. I had an issue of the backend trying to login the user as a session, which is not required. There is a setting REST_SESSION_LOGIN that you can put to False and this solved some problems for me.

**Comment by philippeluickx** [comment]
So there is indeed a bug here... When first registering with social and then trying to register the same email address, it raises the correct error message. This is because of the form validation, which passes through https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L255

However, the other way around the validation(s?) are skipped because there is no form. Not sure if this is a pointer: https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/models.py#L151

Providers are not responsible for checking whether or
    not an account already exists or not. Therefore, a provider
    typically creates a new (unsaved) `SocialAccount` instance. The
    `User` instance pointed to by the account (`account.user`) may be
    prefilled by the provider for use as a starting point later on
    during the signup process.

**Comment by rggibson** [comment]
Thanks for the tip about REST_SESSION_LOGIN.  I'm pretty new to Django and its rest framework, so I wasn't aware of it.  I'll give it a try.

For what it's worth, I have the following workaround for this issue. using the `facebook-sdk` package

```python
from django.contrib.auth.models import User

from rest_framework.response import Response
from rest_framework import status

from allauth.socialaccount.providers.facebook.views import FacebookOAuth2Adapter
from allauth.socialaccount.models import SocialAccount
from rest_auth.registration.views import SocialLoginView

import facebook

import logging

logger = logging.getLogger( __name__ )

class FacebookLogin( SocialLoginView ):
    adapter_class = FacebookOAuth2Adapter

    # Override post to fix bug where duplicate email already exists                                                                                               
    def post( self, request, *args, **kwargs ):
	message = None

	# Use the access token to get the facebook email                                                                                                          
	fb = facebook.GraphAPI(
            access_token=request.data.get( 'access_token' ) )
	fb_email = fb.get_object( 'me', fields='email' ).get( 'email' )

	# Is this email already in use?                                                                                                                           
	users = User.objects.filter( email=fb_email )
	if len( users ) > 0:
        # Email is in use                                                                                                                                     
        if len( users ) > 1:
		    messge = ( 'Multiple users with email ' + fb_email + ' detected!' )
		    logger.error( message )
        else:
            # Check if the user has a SocialAccount for Facebook                                                                                              
		    q = SocialAccount.objects.filter( user=users[ 0 ],
                                              provider='facebook' )
		    if len( q ) == 0:
                # No social account found, badness                                                                                                            
                message = ( 'Email already in use for a non-Facebook account' )

	if message is None:
        # Call the SocialLoginView's post method                                                                                                              
        return super( FacebookLogin, self ).post( request, args, kwargs )
	else:
        return Response( {
		  'status': 'Unauthorized',
		  'message': message
		  }, status=status.HTTP_401_UNAUTHORIZED )
```

**Comment by bogdanbatog** [comment]
I'm facing the same issue and it seems to happen only when `SOCIALACCOUNT_EMAIL_REQUIRED = True` and the Facebook account has no associated email address (the account may have been set up using only a phone number).

**Comment by alacritythief** [comment]
Hey everyone,

My team uses rest-auth in our production projects and we encountered this error. Our case on how we reached the error might be a bit different but I'd like to add to the discussion here just in case if other folks continue to hit this same exact issue and are looking for solutions.

When a user logged into our app, `'User' object has no attribute 'backend'` was the error received and the user would be created with no username or email causing conflicts with other new users being created.

The main thing that solved this is to make sure to double check your Facebook scopes and fields in your backend and front-end. If your front-end permissions for Facebook don't match up with the backend, you end up with a token containing missing information that creates this error and a bunch of other possible conflicts. The docs for django-allauth were updated recently to reflect changes for the graph api:

```
SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile', 'user_friends'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'FIELDS': [
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
            'verified',
            'locale',
            'timezone',
            'link',
            'gender',
            'updated_time'],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': 'path.to.callable',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v2.4'
    }
}
```

Make sure your front-end using the facebook sdk calls the same scopes. 

Example JS code:
```
  onFacebookLogin = (e) => {
    e.preventDefault();
    const { dispatch } = this.props;

    FB.login((login) => {
      dispatch(ProfileAPI.postFacebookToken(login.authResponse))
        .then((zipcodes) => {
          this.setState({ loading: true });
          dispatch(WeatherAPI.clearWeatherData());

          return Promise.all([
            zipcodes.split(',').filter(zip => zip).map(function(zipcode, index) {
              return dispatch(WeatherAPI.getWorldData({ zipcode }, index));
            })]);
        })
        .then(() => {
          this.setState({ loading: false });
        });
    }, **{ scope: 'email, public_profile, user_friends' })**;
    dispatch(AppAPI.loginToggle(false));
  };
```

Doing so fixed the issue for us and users were created just fine. It might be best to add this to the documentation for people to make sure to check this when creating SPA/Stateless apps.

**Comment by philippeluickx** [comment]
+1 on adding this to docs.
Would it also be possible to catch these situations more elegantly in the backend?

**Comment by vipulsayone** [comment]
I have the same issue '** 'User' object has no attribute 'backend** when tries to login with google , the issue happens if there is already a user with the same email registered. it creates a duplicate entry.

**Comment by commilfo** [comment]
I get the same issue

> Traceback (most recent call last):
  File "\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "\rest_framework\views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "\rest_framework\views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "\rest_auth\views.py", line 51, in post
    self.login()
  File "\rest_auth\views.py", line 41, in login
    login(self.request, self.user)
  File "\django\contrib\auth\__init__.py", line 112, in login
    request.session[BACKEND_SESSION_KEY] = user.backend
AttributeError: 'Account' object has no attribute 'backend'

when I login through Facebook with an email which already exists for some other user.
A new user is created with the same email but without username. And then it fails with the above error.

If I login through Facebook and there's no other user with the same email, everything is Ok and a new user is created (with username this time).

**Comment by matheuscas** [comment]
I'm having the same problem, but with Linkedin login. Following @alacritythief recommendation, this error is solved, however another one comes up: `UNIQUE constraint failed: auth_user.username`. Yes, I already a user with the same username, but the behavior should be a HTTP error response or even create a new user with username+number. Or am I wrong? I'll keep digging.

**Comment by philippeluickx** [comment]
I am having following error:

`duplicate` key value violates unique constraint "users_user_username_key"
DETAIL:  Key (username)=() already exists.

This happens when a user logs in with LinkedIn when he has an account created the normal way already. What happens is somehow the username is not used when creating a new account, however a check should be done and an error reported mentioning that this email has an account already.

@matheuscas  what is your use case?

**Comment by matheuscas** [comment]
@philippeluickx It's not my case, unfortunately. The first linkedIn user was created through the browser. Now I'm trying again through the API, using the same token and the "app code" from linkedIn.

**Comment by philippeluickx** [comment]
@matheuscas allauth normally creates the username based on the received email address and adds a number to it if that username already exists. Are you sure you have a username defined or does it just return an empty username?

**Comment by matheuscas** [comment]
@philippeluickx Yes and no (I'll explain). I found myself in a odd situation. First, some data. My settings:

```python
AUTHENTICATION_BACKENDS = (

    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',

)

# auth and allauth settings
LOGIN_REDIRECT_URL = '/'
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'SCOPE': ['email', 'public_profile'],
        'METHOD': 'js_sdk'  # instead of 'oauth2'
    },
    'google': {
        'SCOPE': ['profile', 'email'],
          'AUTH_PARAMS': { 'access_type': 'online' }
    },
    'linkedin_oauth2':{
        'SCOPE':['r_basicprofile', 'r_emailaddress']
    },
    'linkedin':{
        'SCOPE':['r_basicprofile', 'r_emailaddress']
    }
}

ACCOUNT_SIGNUP_FORM_CLASS = 'social.forms.UserSignupForm'
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
```
And here are my scenarios:
**First scenario**:  4 users (1 superuser, 1 LinkedIn through browser and 2 from the other providers), 3 social accounts and, as expected, 3 social tokens related. 
Doing a post to LinkedIn I receive this: `'User' object has no attribute 'backend'`, but even though  a social token is created, a social account is created with **empty user** e a **complete empty user** is created too (I'm not using custom user model, for now). 

**Second scenario**: using the first and doing the POST again. I receive this: `UNIQUE constraint failed: auth_user.username`. What a day, huh?

**Comment by philippeluickx** [comment]
Do you have all your settings correct for LinkedIn? In https://www.linkedin.com/developer/apps/ make sure you get basic_profile and emailaddress.

Can you be a bit more specific about the following:
1. 1 LinkedIn via browser = through admin or standard django or REST? This user has a social account associated?
2. What post do you do to LinkedIn? Are you trying to connect a new user or login with the existing LI user?
3. Your second scenario is just repeating the first scenario?

**Comment by matheuscas** [comment]
Here my app permissions:

![captura de tela 2016-05-25 as 10 35 58](https://cloud.githubusercontent.com/assets/4574315/15541820/98c1e542-2264-11e6-81ab-7c464d7b0b77.png)

1- Through a regular social login button like bellow, that I created using django-allAuth. And yes, this user has a social account associated. 

![signin-button](https://cloud.githubusercontent.com/assets/4574315/15541889/e57ff82e-2264-11e6-9094-7693cc9bf842.png)

2- I'm trying a registration POST like this:

```
POST http://localhost:8000/social/rest-auth/linkedin/

Body: 
{
    "access_token": "my_ access_token",
    "code": "my_app_code"
}
```
3- In the second scenario I'm doing the same in the first, but having the odd data created (empty user, etc.) in the first scenario.

**Comment by philippeluickx** [comment]
Not sure if it has an impact, but LinkedIn only uses the access_token. So no need to include the code (that's e.g. with Facebook in some implementations).

In all fairness, I also noticed that the whole social account is a mess to debug. My production environment behaves different than my dev environment. Not sure if that has to do with how access_tokens work. I am at the moment trying to figure out why...

**Comment by matheuscas** [comment]
Yeah, removing `code`does not cause any damage, however it does not solve any problems either, unfortunately. Thank man, I'll keep looking.

**Comment by philippeluickx** [comment]
I'm looking into something similar, will keep this thread updated if I gain any insights. Please do the same! And good luck...

**Comment by philippeluickx** [comment]
So I have done some digging into allauth. Seems like at this spot there is a check done to see if an account with the same email address exists already:
https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/adapter.py#L139

This is then passed back to the calling function on
https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/helpers.py#L25

    if not auto_signup:
        request.session['socialaccount_sociallogin'] = sociallogin.serialize()
        url = reverse('socialaccount_signup')
        ret = HttpResponseRedirect(url)


The problem is that by then, we already have a new user created that does not have the username filled out. The normal flow on allauth then probably fixes the whole situation somehow, but with the rest-auth, this is the state that remains and causes issues (at least for me).

So I have the impression we should do the check earlier. Not everything is clear to me yet, but a quick fix could be to simply check in the serializer validation if the email exists already.

Fork coming up, feedback welcome!

**Comment by philippeluickx** [comment]
Allright, getting some insights here.
Basically things get messed up at parts of allauth where a redirect is part of the flow, such as

https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/helpers.py#L25

```
    if not auto_signup:
        request.session['socialaccount_sociallogin'] = sociallogin.serialize()
        url = reverse('socialaccount_signup')
        ret = HttpResponseRedirect(url)
```


It would make sense that any HttpResponseRedirect encountered, will result in weird artefacts in rest-auth.

The other thing to consider in the whole "User object has no attribute backend" is that up until https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/registration/serializers.py#L112 there is a user created, but not yet saved to the backend. If this user model at this stage has an issue (such as in my case a username that is left blank), then problems will happen in the next step
`login.save(request, connect=True)`

I am working on a quick fix that would do a check before saving at this stage to see if there is a problem. But I don't want to do a simple check on username, as some User models might not have username...
So in my use case, I think the issue is caused because of UNIQUE_EMAIL setting that is leading to this redirect. I might not cover all problems with this check and I feel somehow it's a hack, but it'll help me at least.

**Comment by Noaiii** [comment]
I have this problem when I start Twitter Login.
And I fix it by this:
`REST_SESSION_LOGIN = False`
To enable session login in Login API view (default: True).
By setting this, django_login() will not be performed.
