### ISSUE TITLE
Error while signing up Duplicate user using Google login

### ISSUE THREAD

**Issue by roopesh90** [Tivix/django-rest-auth#92]
I've integrated Facebook social signing before implementing Google Plus sign in.
I have a case where a user has signed in using Facebook, and is using the same email id in Google Plus and signing into the app. On doing so, I get the following error:

```
Internal Server Error: /api-auth/auth/google/
Traceback (most recent call last):
  File "/home/user/projectfolder/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/projectfolder/venv/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/user/projectfolder/venv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/projectfolder/venv/local/lib/python2.7/site-packages/rest_framework/views.py", line 456, in dispatch
    response = self.handle_exception(exc)
  File "/home/user/projectfolder/venv/local/lib/python2.7/site-packages/rest_framework/views.py", line 453, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/user/projectfolder/venv/local/lib/python2.7/site-packages/rest_auth/views.py", line 54, in post
    if not self.serializer.is_valid():
  File "/home/user/projectfolder/venv/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 191, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/user/projectfolder/venv/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 374, in run_validation
    value = self.validate(value)
  File "/home/user/projectfolder/venv/local/lib/python2.7/site-packages/rest_auth/registration/serializers.py", line 38, in validate
    complete_social_login(request, login)
  File "/home/user/projectfolder/venv/local/lib/python2.7/site-packages/allauth/socialaccount/helpers.py", line 145, in complete_social_login
    return _complete_social_login(request, sociallogin)
  File "/home/user/projectfolder/venv/local/lib/python2.7/site-packages/allauth/socialaccount/helpers.py", line 161, in _complete_social_login
    ret = _process_signup(request, sociallogin)
  File "/home/user/projectfolder/venv/local/lib/python2.7/site-packages/allauth/socialaccount/helpers.py", line 28, in _process_signup
    url = reverse('socialaccount_signup')
  File "/home/user/projectfolder/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 551, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/user/projectfolder/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 468, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'socialaccount_signup' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
```

**Comment by citizen-stig** [comment]
Problem described here https://github.com/Tivix/django-rest-auth/issues/86
Short term solution, add url with name 'socialaccount_signup'

**Comment by illing2005** [comment]
I you want that the two social-accounts are combined to one user you can use my fork:
https://github.com/illing2005/django-rest-auth

This is kind of a hack because it introduces some security issues:
https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/adapter.py#L136

But if you only use google plus and facebook where email addresses are verified, it should be OK.
